import pool from "./index";

/**
 * Fetch every row from the ingredient table.
 */
export function getIngredients(): Promise<App.IngredientRow[]> {
  return pool
    .query("SELECT id, name, ingredient_type FROM ingredient")
    .then((result) => result.rows as App.IngredientRow[]);
}

/**
 * Build a slug from an ingredient name: trimmed, lower-cased, with runs of
 * whitespace collapsed to single underscores. e.g. "  Garlic Clove " ->
 * "garlic_clove".
 */
function slugify(name: string): string {
  return String(name == null ? "" : name)
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "_");
}

/**
 * Insert new ingredients into the ingredient table. The uuid id is generated by
 * the database, and the slug is derived from the name.
 */
export function addIngredients(
  ingredients: App.NewIngredient[]
): Promise<App.SavedIngredient[]> {
  if (!ingredients || !ingredients.length) {
    return Promise.resolve([]);
  }

  const values: string[] = [];
  const rows = ingredients.map((ing, i) => {
    const base = i * 3;
    values.push(ing.name, ing.type, slugify(ing.name));
    return "($" + (base + 1) + ", $" + (base + 2) + ", $" + (base + 3) + ")";
  });

  const sql =
    "INSERT INTO ingredient (name, ingredient_type, slug) VALUES " +
    rows.join(", ") +
    " RETURNING id, name, ingredient_type, slug";

  return pool
    .query(sql, values)
    .then((result) => result.rows as App.SavedIngredient[]);
}
