import { query } from "./index";

/**
 * Fetch every row from the ingredient table.
 */
export function getIngredients(): Promise<App.IngredientRow[]> {
  return query<App.IngredientRow>(
    "SELECT id, name, ingredient_type FROM ingredient"
  );
}

/**
 * Build a slug from an ingredient name: trimmed, lower-cased, with runs of
 * whitespace collapsed to single underscores. e.g. "  Garlic Clove " ->
 * "garlic_clove".
 */
function slugify(name: string): string {
  return String(name == null ? "" : name)
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "_");
}

/**
 * Insert new ingredients into the ingredient table. The uuid id is generated by
 * the database, and the slug is derived from the name.
 */
export function addIngredients(
  ingredients: App.NewIngredient[]
): Promise<App.SavedIngredient[]> {
  if (!ingredients || !ingredients.length) {
    return Promise.resolve([]);
  }

  const values: string[] = [];
  const rows = ingredients.map((ing, i) => {
    const base = i * 3;
    values.push(ing.name, ing.type, slugify(ing.name));
    return "($" + (base + 1) + ", $" + (base + 2) + ", $" + (base + 3) + ")";
  });

  const sql =
    "INSERT INTO ingredient (name, ingredient_type, slug) VALUES " +
    rows.join(", ") +
    " RETURNING id, name, ingredient_type, slug";

  return query<App.SavedIngredient>(sql, values);
}

/**
 * Update an ingredient's name and type (the slug is re-derived from the name).
 * Resolves with the updated row, or null when no ingredient with that id exists.
 */
export function updateIngredient(
  id: string,
  name: string,
  type: App.IngredientType
): Promise<App.SavedIngredient | null> {
  return query<App.SavedIngredient>(
    "UPDATE ingredient SET name = $1, ingredient_type = $2, slug = $3 " +
      "WHERE id = $4 RETURNING id, name, ingredient_type, slug",
    [name, type, slugify(name), id]
  ).then((rows) => rows[0] || null);
}

/**
 * Delete a single ingredient by id. Resolves true when a row was actually
 * removed, false when no ingredient with that id existed.
 */
export function deleteIngredient(id: string): Promise<boolean> {
  return query<{ id: string }>(
    "DELETE FROM ingredient WHERE id = $1 RETURNING id",
    [id]
  ).then((rows) => rows.length > 0);
}
